export const MOVIES_GET_REQUEST = "MOVIES_GET_REQUEST"
export const MOVIES_GET_SUCCESS = "MOVIES_GET_SUCCESS"
export const MOVIES_GET_FAIL = "MOVIES_GET_FAIL"

export const MOVIES_ADD_REQUEST = "MOVIES_ADD_REQUEST"
export const MOVIES_ADD_SUCCESS = "MOVIES_ADD_SUCCESS"
export const MOVIES_ADD_FAIL = "MOVIES_ADD_FAIL"

export const MOVIES_GET_ID_REQUEST = "MOVIES_GET_ID_REQUEST"
export const MOVIES_GET_ID_SUCCESS = "MOVIES_GET_ID_SUCCESS"
export const MOVIES_GET_ID_FAIL = "MOVIES_GET_ID_FAIL"

export const MOVIES_GET_TITLE_REQUEST = "MOVIES_GET_TITLE_REQUEST"
export const MOVIES_GET_TITLE_SUCCESS = "MOVIES_GET_TITLE_SUCCESS"
export const MOVIES_GET_TITLE_FAIL = "MOVIES_GET_TITLE_FAIL"

export const MOVIES_EMAIL_REQUEST = "MOVIES_EMAIL_REQUEST"
export const MOVIES_EMAIL_SUCCESS = "MOVIES_EMAIL_SUCCESS"
export const MOVIES_EMAIL_FAIL = "MOVIES_EMAIL_FAIL"
